### PR TITLE
Upgrade to Keycloak 4.2.1 and Activiti Realm

### PR DESCRIPTION
**Pull request by salaboy**
I've upgraded Keycloak to 4.2.1 Final, which is the latest stable release of Keycloak. 
The main reason behind the upgrade is that it is Final and also the client libraries are now updated to support Spring Boot 2. 

I've modified the base realm which was a mock that the Activiti Team was using. We are currently defining more clear name for our Roles and Groups, and you will see the changes in the realm that now contains: ACTIVITI_USER and ACTIVITI_ADMIN. We will include ACTIVITI_MODELING for the modelling app soon. 

If there are other project using Keycloak, I would recommend to have completely isolated REALMS for such projects.

### CODE REVIEW

**Comment by rgauss** [comment]
As [mentioned in another open PR](https://github.com/Alfresco/alfresco-keycloak-deployment/pull/19#issuecomment-395482805) here and discussed in meetings:

1.  We'll soon be archiving this project in favor of [alfresco-identity-service](https://github.com/Alfresco/alfresco-identity-service).  Please raise any PRs there.

2. We'd prefer to use the common [alfresco-realm](https://github.com/Alfresco/alfresco-identity-service/blob/master/alfresco-realm.json) if possible.

**Comment by magemello** [comment]
Can we avoid name like ACTIVITI_ that will make the migration from community to enterprise complicated?

**Comment by Salaboy** [comment]
@magemello I think that we should deal with APS in a way that extends community not redefine things. ACTIVITI_USER means something specific for activiti, so using just "user" doesn't cut it.

**Comment by Salaboy** [comment]
@rgauss I don't think that with a single realm we can achieve everything. If we want to differentiate what an user mean from other services, having a REALM per domain will make sense. Is there someone making any definitions about what an USER is? Is that part of Identity Services? we will stop using this project then.. It might be good to add such news in a section in the README file to make sure that nobody consume this one.

**Comment by Salaboy** [comment]
@rgauss it seems that identity-services is just a HELM chart.. meaning that I can probably bootstrap it overriding the alfresco realm with the activiti community one: 
https://github.com/Alfresco/alfresco-identity-service/blob/master/helm/alfresco-identity-service/values.yaml#L24

Is that OK for you guys? I'm not sure that this is the best place to discuss it.. but I need to see if that is a blessed approach.

**Comment by Salaboy** [comment]
@rgauss we are ok in most of the points besides our integration tests. Our integration tests depends on docker images right now and changing all of those to work with kubernetes is in our plans, but we cannot do that in the short term. So we need to sort this out for now. 

As you mention, we can override the realm for now (However, we made sure the realm could be easily overridden (also see AUTH-118)) as well as an intermediate step. I know that is not the best option, but after having discussions with the APS team, they are doing something similar. It seems that everyone will need a different set of users with different set of roles and centralising that definition now is just slowing us down. 

Notice that the only reason why we need this intermediate step right now is to move forward the community bits. The users that we have in our realm are just the necessary ones for our examples and acceptance tests. I don't see the value of having those in the alfresco realm, who else is going to use those users?

**Comment by rgauss** [comment]
As discussed during our meeting yesterday, this repo can be moved back into the Activiti GitHub org (or a new repo can be used), clearly indicating in the name and description that it is only for purposes of integration testing and that development and production should use the [alfresco-identity-service](https://github.com/Alfresco/alfresco-identity-service) (consumed through the [alfresco-infrastructure-deployment](https://github.com/Alfresco/alfresco-infrastructure-deployment) chart).

In the future the integration tests will be refactored to use the Identity Service as well.

In general, we will likely need solutions to be able bootstrap roles and groups (and potentially even users) but until that functionality is in place we can expect different examples to override the default Identity Service realm to provide that config, though those example realms should minimize differences from the default realm.

**Comment by salaboy** [comment]
I am closing this one.. because it doesn't seems that is going to be merged.

**Pull request closed without merging**
